# Site settings
title: "Fabian Lander - Mathematics"
url: 'https://fabianlander.github.io'
baseurl: ''

author:
  name: Fabian Lander
  email: landerfabian at gmail dot com

# Pagination
paginate: 5
paginate_path: "/page:num/"

# Build settings
markdown: kramdown
highlighter: rouge

include:
  - dist


# Plugins
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-picture-tag  # Added for WebP generation

# Permalinks
permalink: pretty

# Custom vars
version: 1.1.0
google_analytics_id: #UA-XXXX-Y

# Compression settings
sass:
  style: compressed
  
compress_html:
  clippings: all
  comments: all
  endings: all
  ignore:
    envs: []
  blanklines: false
  profile: false
  startings: []

# Picture tag settings
picture:
  source: "assets/images"
  output: "assets/images/generated"
  suppress_warnings: true